### ISSUE TITLE
Plugin not functioning

### ISSUE THREAD

**Issue by loohue** [havatv/qgislinedirectionhistogramplugin#4]
Hi there, I'm relatively new to the world of plugins, so this may be attributed to user error, but the newest version of the plugin doesn't seem to be working. It allows me to select the layer, change the number of bins and browse to the output location, but nothing happens when I click "ok".  I've tried this on both Mac and PC versions of QGIS and have the same problem on both. Thank you!

**Comment by havatv** [comment]
Thank you for reporting.  The plugin seems to be working correctly for me on Windows and Linux (Ubuntu), so it could have something to do with your data set.  If you are able to share your data set, I can have a look.

**Comment by loohue** [comment]
Hi Havard,

Thanks so much for replying. I was trying the tool on Ubuntu and Windows as
well but having the same problem...looks like it is likely my dataset,
which is attached here if you have a minute to try it out.

Thank you!

~Lacey

On Fri, Jul 24, 2015 at 1:44 AM, Håvard Tveite notifications@github.com
wrote:

> Thank you for reporting. The plugin seems to be working correctly for me
> on Windows and Linux (Ubuntu), so it could have something to do with your
> data set. If you are able to share your data set, I can have a look.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/havatv/qgislinedirectionhistogramplugin/issues/4#issuecomment-124444999
> .

## 

Lacey Hughey
Ph.D. student
McCauley Lab https://labs.eemb.ucsb.edu/mccauley/doug/index.html
Dept. of Ecology, Evolution, and Marine Biology
University of California, Santa Barbara

Building 408, Room 116
email: lacey.hughey@gmail.com

**Comment by havatv** [comment]
Apparently it is not possible to upload / attach files on github, so you will have to find somewhere else to upload them, or you could send them to me in an email.

**Comment by loohue** [comment]
Hi Havard,

I am replying over email, but I see that it's likely to an encrypted
address via github. Can you send me your email address?

Thank you!

~Lacey

On Wed, Jul 29, 2015 at 1:50 PM, Håvard Tveite notifications@github.com
wrote:

> Apparantly it is not possible to upload / attach files on github, so you
> will have to find somewhere else to upload them, or you could send them to
> me in an email.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/havatv/qgislinedirectionhistogramplugin/issues/4#issuecomment-126092283
> .

## 

Lacey Hughey
Ph.D. student
McCauley Lab https://labs.eemb.ucsb.edu/mccauley/doug/index.html
Dept. of Ecology, Evolution, and Marine Biology
University of California, Santa Barbara

Building 408, Room 116
email: lacey.hughey@gmail.com

**Comment by havatv** [comment]
I don't have your email address (everything goes though github), and I can't find it on github.  I think you will be able to find my email address on github, as it should be public.

**Comment by havatv** [comment]
Lacey followed up in an email:

> Turns out the problem was on my end- I had some lines that weren't properly segmented so they had multiple "angles" in a single line. When I fixed that, the plug in worked perfectly

Closing.
